# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: helloworld.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'helloworld.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10helloworld.proto\"\x1e\n\nMsgCliente\x12\x10\n\x08mensagem\x18\x01 \x01(\t\"\x1f\n\x0bMsgServidor\x12\x10\n\x08mensagem\x18\x01 \x01(\t24\n\x07Greeter\x12)\n\nHelloWorld\x12\x0b.MsgCliente\x1a\x0c.MsgServidor\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'helloworld_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MSGCLIENTE']._serialized_start=20
  _globals['_MSGCLIENTE']._serialized_end=50
  _globals['_MSGSERVIDOR']._serialized_start=52
  _globals['_MSGSERVIDOR']._serialized_end=83
  _globals['_GREETER']._serialized_start=85
  _globals['_GREETER']._serialized_end=137
# @@protoc_insertion_point(module_scope)
