# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import calculadora_pb2 as calculadora__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in calculadora_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CalcStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Soma = channel.unary_unary(
                '/Calc/Soma',
                request_serializer=calculadora__pb2.Valores.SerializeToString,
                response_deserializer=calculadora__pb2.Resultado.FromString,
                _registered_method=True)
        self.Subtracao = channel.unary_unary(
                '/Calc/Subtracao',
                request_serializer=calculadora__pb2.Valores.SerializeToString,
                response_deserializer=calculadora__pb2.Resultado.FromString,
                _registered_method=True)
        self.Multiplicacao = channel.unary_unary(
                '/Calc/Multiplicacao',
                request_serializer=calculadora__pb2.Valores.SerializeToString,
                response_deserializer=calculadora__pb2.Resultado.FromString,
                _registered_method=True)
        self.Divisao = channel.unary_unary(
                '/Calc/Divisao',
                request_serializer=calculadora__pb2.Valores.SerializeToString,
                response_deserializer=calculadora__pb2.Resultado.FromString,
                _registered_method=True)


class CalcServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Soma(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subtracao(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Multiplicacao(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Divisao(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalcServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Soma': grpc.unary_unary_rpc_method_handler(
                    servicer.Soma,
                    request_deserializer=calculadora__pb2.Valores.FromString,
                    response_serializer=calculadora__pb2.Resultado.SerializeToString,
            ),
            'Subtracao': grpc.unary_unary_rpc_method_handler(
                    servicer.Subtracao,
                    request_deserializer=calculadora__pb2.Valores.FromString,
                    response_serializer=calculadora__pb2.Resultado.SerializeToString,
            ),
            'Multiplicacao': grpc.unary_unary_rpc_method_handler(
                    servicer.Multiplicacao,
                    request_deserializer=calculadora__pb2.Valores.FromString,
                    response_serializer=calculadora__pb2.Resultado.SerializeToString,
            ),
            'Divisao': grpc.unary_unary_rpc_method_handler(
                    servicer.Divisao,
                    request_deserializer=calculadora__pb2.Valores.FromString,
                    response_serializer=calculadora__pb2.Resultado.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Calc', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Calc', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Calc(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Soma(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Calc/Soma',
            calculadora__pb2.Valores.SerializeToString,
            calculadora__pb2.Resultado.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subtracao(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Calc/Subtracao',
            calculadora__pb2.Valores.SerializeToString,
            calculadora__pb2.Resultado.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Multiplicacao(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Calc/Multiplicacao',
            calculadora__pb2.Valores.SerializeToString,
            calculadora__pb2.Resultado.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Divisao(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Calc/Divisao',
            calculadora__pb2.Valores.SerializeToString,
            calculadora__pb2.Resultado.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
