# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculadora.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'calculadora.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63\x61lculadora.proto\")\n\x07Valores\x12\x0e\n\x06valor1\x18\x01 \x01(\x01\x12\x0e\n\x06valor2\x18\x02 \x01(\x01\"\x1e\n\tResultado\x12\x11\n\tresultado\x18\x01 \x01(\x01\x32\x97\x01\n\x04\x43\x61lc\x12\x1e\n\x04Soma\x12\x08.Valores\x1a\n.Resultado\"\x00\x12#\n\tSubtracao\x12\x08.Valores\x1a\n.Resultado\"\x00\x12\'\n\rMultiplicacao\x12\x08.Valores\x1a\n.Resultado\"\x00\x12!\n\x07\x44ivisao\x12\x08.Valores\x1a\n.Resultado\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculadora_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VALORES']._serialized_start=21
  _globals['_VALORES']._serialized_end=62
  _globals['_RESULTADO']._serialized_start=64
  _globals['_RESULTADO']._serialized_end=94
  _globals['_CALC']._serialized_start=97
  _globals['_CALC']._serialized_end=248
# @@protoc_insertion_point(module_scope)
